### PR TITLE
Debian8 compatibility

### PR DESCRIPTION
**Pull request by Demonsthere**
Hey guys,
I have added the compatibility for debian8 and done some cleanup. Feel free to pull it,
Cheers ;-)

### CODE REVIEW

**Comment by Demonsthere** [comment]
The issues have been addressed.

**Comment by cluk1** [comment]
I just spend some time looking at your request. Thanks a lot for your work on making this work with debian jessie. 
But I think some of the changes can not be merged right away. :)
- If we change the box url to point to a hybris internal server than this cookbook will work for no one outside of hybris. 
- it would be great to split this request into several request like:
  - fixing rubocop errors
  - adding serverspec tests
  - adding debian8 compatibility
- As we are using this cookbook for our training material and as we do not have written enough tests here ;) I do not feel comfortable in merging it, sorry.

**Comment by cluk1** [comment]
I tried to integrate all those fixed now. It would be great if you could check if it is working for you.
Thanks.

**Comment by Demonsthere** [comment]
Hey, sorry to hear about the merge fail. 

EDIT: That was an internal error of our wrapper, seems that the cookbook works fine now. Good job :)

**Pull request closed without merging**
